# Generated by Django 5.2.8 on 2025-12-03 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        help_text="Profile being blocked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to="profiles.profile",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        help_text="Profile that initiated the block",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "blocks",
                "indexes": [
                    models.Index(fields=["blocker", "blocked"], name="blocks_blocker_4de809_idx"),
                    models.Index(fields=["blocker"], name="blocks_blocker_42b25f_idx"),
                    models.Index(fields=["blocked"], name="blocks_blocked_0ecc50_idx"),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment"),
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("other", "Other"),
                        ],
                        help_text="Reason for the report",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description of the issue")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        help_text="Current status of the report",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when report was reviewed", null=True
                    ),
                ),
                (
                    "reported",
                    models.ForeignKey(
                        help_text="Profile being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to="profiles.profile",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="Profile that submitted the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to="profiles.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who reviewed the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "indexes": [
                    models.Index(fields=["reporter"], name="reports_reporte_5cbb43_idx"),
                    models.Index(fields=["reported"], name="reports_reporte_dd1cb9_idx"),
                    models.Index(fields=["status"], name="reports_status_e83c1d_idx"),
                    models.Index(fields=["created_at"], name="reports_created_c5f642_idx"),
                ],
            },
        ),
    ]
