# Generated by Django 5.2.8 on 2026-02-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0003_add_search_vector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("toxicity_score", models.FloatField()),
                ("flagged_categories", models.JSONField(default=list)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("shadowban", "Shadowban Applied"),
                            ("warning", "Warning Issued"),
                        ],
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_results",
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "moderation_results",
                "indexes": [
                    models.Index(fields=["message"], name="moderation__message_c4832f_idx"),
                    models.Index(fields=["user"], name="moderation__user_id_4a88cc_idx"),
                    models.Index(fields=["toxicity_score"], name="moderation__toxicit_50fd50_idx"),
                    models.Index(fields=["processed_at"], name="moderation__process_ab87ad_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Shadowban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.TextField()),
                ("duration_hours", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowbans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shadowbans",
                "indexes": [
                    models.Index(fields=["user"], name="shadowbans_user_id_d7b9d0_idx"),
                    models.Index(fields=["is_active"], name="shadowbans_is_acti_b3b96e_idx"),
                    models.Index(fields=["expires_at"], name="shadowbans_expires_3a4e7d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ViolationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("toxicity", "High Toxicity Content"),
                            ("harassment", "Harassment"),
                            ("violence", "Violence"),
                            ("self_harm", "Self Harm"),
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                        ],
                        max_length=50,
                    ),
                ),
                ("toxicity_score", models.FloatField()),
                ("content_snippet", models.TextField(max_length=200)),
                ("action_taken", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "violation_history",
                "indexes": [
                    models.Index(fields=["user"], name="violation_h_user_id_675e75_idx"),
                    models.Index(fields=["is_active"], name="violation_h_is_acti_5d0103_idx"),
                    models.Index(fields=["expires_at"], name="violation_h_expires_d9ac04_idx"),
                    models.Index(fields=["created_at"], name="violation_h_created_fcf669_idx"),
                ],
            },
        ),
    ]
