# Generated by Django 5.2.8 on 2025-12-03 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the match is still active"
                    ),
                ),
                (
                    "profile1",
                    models.ForeignKey(
                        help_text="First profile in the match",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_profile1",
                        to="profiles.profile",
                    ),
                ),
                (
                    "profile2",
                    models.ForeignKey(
                        help_text="Second profile in the match",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_profile2",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["profile1", "is_active"], name="matches_profile_bf1f20_idx"
                    ),
                    models.Index(
                        fields=["profile2", "is_active"], name="matches_profile_450fb8_idx"
                    ),
                    models.Index(fields=["matched_at"], name="matches_matched_8910be_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Swipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        help_text="Direction of swipe: left (reject) or right (accept)",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "swiped",
                    models.ForeignKey(
                        help_text="Profile that was swiped on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes_received",
                        to="profiles.profile",
                    ),
                ),
                (
                    "swiper",
                    models.ForeignKey(
                        help_text="Profile that performed the swipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes_made",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "swipes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["swiper", "created_at"], name="swipes_swiper__31c3ee_idx"),
                    models.Index(fields=["swiped", "created_at"], name="swipes_swiped__8a76ff_idx"),
                ],
                "unique_together": {("swiper", "swiped")},
            },
        ),
    ]
