# Generated by Django 5.2.8 on 2025-12-02 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Chatroom name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Chatroom description")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the chatroom is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member_count",
                    models.IntegerField(default=0, help_text="Number of members in the chatroom"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the chatroom",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chatrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chatrooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("voice", "Voice"),
                            ("system", "System"),
                        ],
                        default="text",
                        help_text="Type of message",
                        max_length=10,
                    ),
                ),
                (
                    "media_url",
                    models.CharField(
                        blank=True, help_text="URL to media file if applicable", max_length=500
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been edited"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been deleted"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="Whether the message is pinned"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chatroom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chatroom this message belongs to (null for match messages)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Profile that sent this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("emoji", models.CharField(help_text="Emoji reaction", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Message being reacted to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat.message",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Profile that reacted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "message_reactions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Message that was read",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="chat.message",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Profile that read the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "read_receipts",
                "ordering": ["read_at"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chatroom", "created_at"], name="messages_chatroo_ce37ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="messages_sender__6ae55a_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["is_pinned"], name="messages_is_pinn_d0688d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "profile", "emoji")},
        ),
        migrations.AlterUniqueTogether(
            name="readreceipt",
            unique_together={("message", "profile")},
        ),
    ]
