# Generated by Django 5.2.8 on 2025-12-03 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("matchmaking", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="match",
            field=models.ForeignKey(
                blank=True,
                help_text="Match this message belongs to (null for chatroom messages)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="matchmaking.match",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["match", "created_at"], name="messages_match_i_33be21_idx"),
        ),
    ]
