# Generated by Django 5.2.8 on 2025-12-03 05:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def populate_search_vector(apps, schema_editor):
    """Populate search_vector for existing messages"""
    Message = apps.get_model('chat', 'Message')
    db_alias = schema_editor.connection.alias
    
    # Update search vector for all existing messages
    Message.objects.using(db_alias).update(
        search_vector=django.contrib.postgres.search.SearchVector('content')
    )


def create_search_trigger(apps, schema_editor):
    """Create trigger to automatically update search_vector on insert/update"""
    schema_editor.execute("""
        CREATE TRIGGER messages_search_vector_update
        BEFORE INSERT OR UPDATE ON messages
        FOR EACH ROW EXECUTE FUNCTION
        tsvector_update_trigger(
            search_vector, 'pg_catalog.english', content
        );
    """)


def drop_search_trigger(apps, schema_editor):
    """Drop the search vector trigger"""
    schema_editor.execute("""
        DROP TRIGGER IF EXISTS messages_search_vector_update ON messages;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_match_message_messages_match_i_33be21_idx"),
        ("matchmaking", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="messages_search__f11ac9_gin"
            ),
        ),
        migrations.RunPython(populate_search_vector, migrations.RunPython.noop),
        migrations.RunPython(create_search_trigger, drop_search_trigger),
    ]
