# Generated by Django 5.2.8 on 2026-02-04 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_add_search_vector"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(help_text="Confession content")),
                (
                    "is_approved",
                    models.BooleanField(default=False, help_text="Whether confession is approved"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether confession is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chatroom",
                    models.ForeignKey(
                        help_text="Chatroom this confession belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confessions",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Profile that created this confession (kept for moderation)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_confessions",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "confessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField(help_text="Poll question")),
                ("options", models.JSONField(help_text="Poll options as JSON array")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the poll is active"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="Poll expiration time", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chatroom",
                    models.ForeignKey(
                        help_text="Chatroom this poll belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Profile that created this poll",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_polls",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("option_index", models.IntegerField(help_text="Index of selected option")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="Poll being voted on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="chat.poll",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        help_text="Profile that voted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "poll_votes",
                "ordering": ["created_at"],
                "unique_together": {("poll", "voter")},
            },
        ),
    ]
