# Generated by Django 5.2.8 on 2026-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_confession_poll_pollvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="pin_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the pin should expire and automatically unpin",
                null=True,
            ),
        ),
    ]
