# Generated by Django 5.2.8 on 2026-02-04 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0003_add_search_vector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("wilson_score", models.FloatField(default=0.0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "message_ranking",
                "indexes": [
                    models.Index(fields=["wilson_score"], name="message_ran_wilson__8c1a43_idx"),
                    models.Index(fields=["message"], name="message_ran_message_62a679_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reputation_score", models.FloatField(default=0.0)),
                (
                    "rank_tier",
                    models.CharField(
                        choices=[
                            ("Fresher", "Fresher"),
                            ("Sophomore", "Sophomore"),
                            ("Senior", "Senior"),
                            ("Campus Legend", "Campus Legend"),
                        ],
                        default="Fresher",
                        max_length=20,
                    ),
                ),
                ("total_upvotes_received", models.IntegerField(default=0)),
                ("total_downvotes_received", models.IntegerField(default=0)),
                ("last_tier_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_reputation",
                "indexes": [
                    models.Index(
                        fields=["reputation_score"], name="user_reputa_reputat_ff11e1_idx"
                    ),
                    models.Index(fields=["rank_tier"], name="user_reputa_rank_ti_018a1d_idx"),
                    models.Index(fields=["user"], name="user_reputa_user_id_2e6094_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "votes",
                "indexes": [
                    models.Index(fields=["message"], name="votes_message_74d6ac_idx"),
                    models.Index(fields=["user"], name="votes_user_id_72a822_idx"),
                ],
                "unique_together": {("user", "message")},
            },
        ),
    ]
