# Generated by Django 5.2.8 on 2026-02-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HashedIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_hash", models.CharField(max_length=64, unique=True)),
                ("salt", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashed_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hashed_identities",
                "indexes": [
                    models.Index(fields=["email_hash"], name="hashed_iden_email_h_1269d7_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("post_creation", "Post Creation"),
                            ("comment_creation", "Comment Creation"),
                            ("vote_casting", "Vote Casting"),
                            ("login_attempt", "Login Attempt"),
                            ("api_request", "API Request"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limit_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rate_limit_records",
                "indexes": [
                    models.Index(
                        fields=["user", "action_type", "timestamp"],
                        name="rate_limit__user_id_b6fcdf_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"], name="rate_limit__ip_addr_750a49_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("failed_authentication", "Failed Authentication"),
                            ("xss_attempt", "XSS Attempt"),
                            ("csrf_failure", "CSRF Failure"),
                            ("input_sanitization", "Input Sanitization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("additional_data", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_events",
                "indexes": [
                    models.Index(fields=["event_type"], name="security_ev_event_t_77edde_idx"),
                    models.Index(fields=["severity"], name="security_ev_severit_dac121_idx"),
                    models.Index(fields=["timestamp"], name="security_ev_timesta_96e9ee_idx"),
                    models.Index(fields=["ip_address"], name="security_ev_ip_addr_286f33_idx"),
                ],
            },
        ),
    ]
