# Generated by Django 5.2.8 on 2025-12-02 14:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "anonymous_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public anonymous identifier for this profile",
                        unique=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        help_text="Age must be between 18 and 100",
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interests",
                    models.JSONField(default=list, help_text="Array of interest strings"),
                ),
                ("hobbies", models.JSONField(default=list, help_text="Array of hobby strings")),
                (
                    "relationship_intent",
                    models.CharField(
                        choices=[
                            ("friendship", "Friendship"),
                            ("dating", "Dating"),
                            ("casual", "Casual"),
                        ],
                        help_text="Relationship intent: friendship, dating, or casual",
                        max_length=20,
                    ),
                ),
                (
                    "personality_tags",
                    models.JSONField(default=list, help_text="Array of personality tag strings"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Optional bio text (max 500 characters)",
                        max_length=500,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture with anonymity filters",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
                "indexes": [
                    models.Index(fields=["anonymous_id"], name="profiles_anonymo_a2e145_idx"),
                    models.Index(fields=["user"], name="profiles_user_id_29277a_idx"),
                ],
            },
        ),
    ]
