# Generated by Django 5.2.8 on 2026-07-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="hobbies",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="personality_tags",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="relationship_intent",
        ),
    ]
